name: Zip and Upload .bru files to Slack

on:
  push:
    branches:
      - master

jobs:
  zip-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find and zip .bru files
        run: |
          zip -r bru-collections.zip $(find . -type f -name "*.bru")

      - name: Verify zip file
        run: ls -lh bru-collections.zip  # ✅ Ensure file exists

      - name: Upload zip as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: bru-collections
          path: bru-collections.zip
          if-no-files-found: error

      - name: Debug Slack Token
        run: echo "SLACK_BOT_TOKEN length: ${#SLACK_BOT_TOKEN}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Send zip to Slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: |
          curl -F "file=@bru-collections.zip" \
               -F "initial_comment=Latest API test collections (.bru) after PR merge" \
               -F "channels=C086TFFEVTL" \
               -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
               https://slack.com/api/files.upload
