name: Zip and Upload .bru files to Slack

on:
  push:
    branches:
      - master

jobs:
  zip-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find and zip .bru files
        run: |
          FILES=$(find . -type f -name "*.bru")
          if [ -z "$FILES" ]; then
            echo "No .bru files found!"
            exit 1
          fi
          zip -r bru-collections.zip $FILES

      - name: Verify zip file
        run: |
          if [ ! -s bru-collections.zip ]; then
            echo "bru-collections.zip is empty!"
            exit 1
          fi
          ls -lh bru-collections.zip

      - name: Upload zip as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: bru-collections
          path: bru-collections.zip
          if-no-files-found: error

      - name: Debug Slack Token
        run: |
          if [ -z "${SLACK_BOT_TOKEN}" ]; then
            echo "SLACK_BOT_TOKEN is missing!"
            exit 1
          fi
          echo "SLACK_BOT_TOKEN is set and has ${#SLACK_BOT_TOKEN} characters."
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Send zip to Slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: |
          curl -F "file=@bru-collections.zip" \
               -F "initial_comment=Latest API test collections (.bru) after PR merge" \
               -F "channels=C086TFFEVTL" \
               -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
               https://slack.com/api/files.upload
