name: PR Merge to Main - Zip .bru files and send to Slack

on:
  push:
    branches:
      - master
    types:
      - merged

jobs:
  zip-and-send-to-slack:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Install required tools (zip, curl)
      - name: Install zip and curl
        run: |
          sudo apt-get update
          sudo apt-get install -y zip curl

      # Find .bru files and zip them
      - name: Zip .bru files
        run: |
          # Create a directory for zip files
          mkdir -p zipped_files
          # Find and zip .bru files
          find . -name "*.bru" -exec zip zipped_files/bru_collection.zip {} +

      # Send zip file to Slack
      - name: Send to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          # Prepare the Slack message payload
          curl -X POST -H 'Content-type: application/json' \
            --data '{
              "text": "The .bru file collection is ready and has been zipped. See the latest update!",
              "attachments": [
                {
                  "fallback": "Bru Collection zip",
                  "pretext": "Latest API Test Collection",
                  "title": "bru_collection.zip",
                  "title_link": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                  "text": "Click here to view the details of the CI/CD job.",
                  "file": {
                    "content": "'"$(cat zipped_files/bru_collection.zip)"'" 
                  }
                }
              ]
            }' \
            $SLACK_WEBHOOK_URL
