name: Zip and Upload .bru files to Slack

on:
  push:
    branches:
      - master

jobs:
  zip-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find and zip .bru files
        run: |
          zip -r bru-collections.zip $(find . -type f -name "*.bru")

      - name: Upload zip as artifact (optional)
        uses: actions/upload-artifact@v3
        with:
          name: bru-collections
          path: bru-collections.zip

      - name: Send zip to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -F "file=@bru-collections.zip" \
               -F "initial_comment=Latest API test collections (.bru) after PR merge" \
               -F "channels=#your-slack-channel" \
               -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" \
               https://slack.com/api/files.upload
