---
name: Zip and Upload .bru files to Slack
on:
  push:
    branches:
      - master
jobs:
  zip-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Find and zip .bru files
        run: |
          zip -r bru-collections.zip $(find . -type f -name "*.bru")
      - name: Upload zip as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: bru-collections
          path: bru-collections.zip
          if-no-files-found: error
      - name: Send zip to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: >
          curl -F "file=@bru-collections.zip" \
               -F "initial_comment=Latest API test collections (.bru) after PR merge" \
               -F "channels=#your-slack-channel" \
               -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
               https://slack.com/api/files.upload
